ROBOFLOW_API_KEY = "xxxxxx"
ROBOFLOW_WORKSPACE = ""                       
ROBOFLOW_PROJECT_DET = "brain-tumor-detection-glu2s"
ROBOFLOW_VERSION_DET = "1"
ROBOFLOW_PROJECT_CLS = "brain-tumor-of8ow"
ROBOFLOW_VERSION_CLS = "1"
